# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'App2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resource_rc

class Ui_Form(object):
    def setupUi(self, Form):
        # form
        Form.setObjectName("Form")
        Form.resize(768, 1024)
        Form.setMinimumSize(QtCore.QSize(720, 960))
        Form.setMaximumSize(QtCore.QSize(960, 1280))

        # form icon
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon_window.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)

        # button_menu
        self.button_menu = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHeightForWidth(self.button_menu.sizePolicy().hasHeightForWidth())
        self.button_menu.setSizePolicy(sizePolicy)
        self.button_menu.setMinimumSize(QtCore.QSize(0, 50))
        self.button_menu.setObjectName("button_menu")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon_menu.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_menu.setIcon(icon1)
        # button_gallery
        self.button_gallery = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHeightForWidth(self.button_gallery.sizePolicy().hasHeightForWidth())
        self.button_gallery.setSizePolicy(sizePolicy)
        self.button_gallery.setMinimumSize(QtCore.QSize(0, 50))
        self.button_gallery.setObjectName("button_gallery")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon_gallery.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_gallery.setIcon(icon2)
        # button_credits
        self.button_credits = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHeightForWidth(self.button_credits.sizePolicy().hasHeightForWidth())
        self.button_credits.setSizePolicy(sizePolicy)
        self.button_credits.setMinimumSize(QtCore.QSize(0, 50))
        self.button_credits.setObjectName("button_credits")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icon_credits.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_credits.setIcon(icon3)

        # page1
        self.page1 = QtWidgets.QWidget()
        self.page1.setObjectName("page1")
        # label title
        self.label_title = QtWidgets.QLabel(self.page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHeightForWidth(self.label_title.sizePolicy().hasHeightForWidth())
        self.label_title.setSizePolicy(sizePolicy)
        self.label_title.setMaximumSize(QtCore.QSize(16777215, 86))
        self.label_title.setObjectName("label_title")
        # label_camera
        self.label_camera = QtWidgets.QLabel(self.page1)
        self.label_camera.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_camera.setObjectName("label_camera")
        self.label_camera.setAlignment(QtCore.Qt.AlignCenter)
        # button_snapshot
        self.button_snapshot = QtWidgets.QPushButton(self.page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHeightForWidth(self.button_snapshot.sizePolicy().hasHeightForWidth())
        self.button_snapshot.setSizePolicy(sizePolicy)
        self.button_snapshot.setMinimumSize(QtCore.QSize(0, 50))
        self.button_snapshot.setObjectName("button_snapshot")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icon_snapshot.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_snapshot.setIcon(icon4)
        # button_color
        self.button_color = QtWidgets.QPushButton(self.page1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHeightForWidth(self.button_color.sizePolicy().hasHeightForWidth())
        self.button_color.setSizePolicy(sizePolicy)
        self.button_color.setMinimumSize(QtCore.QSize(0, 50))
        self.button_color.setObjectName("button_color")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icon_color.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_color.setIcon(icon5)

        #page2
        self.page2 = QtWidgets.QWidget()
        self.page2.setObjectName("page2")
        #label_image
        self.label_image = QtWidgets.QLabel(self.page2)
        self.label_image.setText("")
        self.label_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image.setObjectName("label_image")
        
        #page3
        self.page3 = QtWidgets.QWidget()
        self.page3.setObjectName("page3")
        #label_credits
        self.label_credits = QtWidgets.QLabel(self.page3)
        self.label_credits.setObjectName("label_credits")

        # stackwidget
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.stackedWidget.addWidget(self.page1)
        self.stackedWidget.addWidget(self.page2)
        self.stackedWidget.addWidget(self.page3)
        self.stackedWidget.setCurrentIndex(0)

        #layout
        # layout_button
        self.layout_button = QtWidgets.QHBoxLayout()
        self.layout_button.setObjectName("layout_button")
        self.layout_button.addWidget(self.button_snapshot)
        self.layout_button.addWidget(self.button_color)
        # layout_top
        self.layout_top = QtWidgets.QHBoxLayout()
        self.layout_top.setObjectName("layout_top")
        self.layout_top.addWidget(self.button_menu)
        self.layout_top.addWidget(self.button_gallery)
        self.layout_top.addWidget(self.button_credits)
        # layout_main
        self.layout_main = QtWidgets.QVBoxLayout(Form)
        self.layout_main.setObjectName("layout_main")
        self.layout_main.addLayout(self.layout_top)
        self.layout_main.addWidget(self.stackedWidget)
        # layout_page1
        self.layout_page1 = QtWidgets.QVBoxLayout(self.page1)
        self.layout_page1.setObjectName("layout_page1")
        self.layout_page1.addWidget(self.label_title)
        self.layout_page1.addWidget(self.label_camera)
        self.layout_page1.addLayout(self.layout_button)
        # layout_page2
        self.layout_page2 = QtWidgets.QVBoxLayout(self.page2)
        self.layout_page2.setObjectName("layout_page2")
        self.layout_page2.addWidget(self.label_image)
        # layout_page3
        self.layout_page3 = QtWidgets.QVBoxLayout(self.page3)
        self.layout_page3.setObjectName("layout_page3")
        self.layout_page3.addWidget(self.label_credits)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.button_menu.setText(_translate("Form", "Main Menu"))
        self.button_gallery.setText(_translate("Form", "Gallery"))
        self.button_credits.setText(_translate("Form", "Credits"))
        self.label_title.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">SAY SMILE - PyQt5 Photobooth App</span></p></body></html>"))
        self.button_snapshot.setText(_translate("Form", "Take Snapshot"))
        self.button_color.setText(_translate("Form", "Color Change"))
        self.label_credits.setText(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                "p, li { white-space: pre-wrap; }\n"
                                                "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
                                                "<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Made by Dimas Adrian Mukti</p>\n"
                                                "<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">IoT Engineer Intern at Qlue Performa Indonesia</p></body></html>"))
        self.label_image.setText(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                                "p, li { white-space: pre-wrap; }\n"
                                                "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
                                                "<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">No Image</p>\n"))
